bookmarks/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

from main.views import IndexView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', IndexView.as_view(), name='index'),
    path('users/', include('users.urls', namespace='users')),
    path('main/', include('main.urls', namespace='main'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.urls import path

from main.views import BookmarksListView, add_bookmark

app_name = 'main'

urlpatterns = [
    path('my-bookmarks/', BookmarksListView.as_view(), name='my-bookmarks'),
    path('add-bookmark/', add_bookmark, name='add-bookmark')
]

users/urls.py
from django.contrib.auth.views import LogoutView
from django.urls import path

from users.views import UserLoginView, UserRegistrationView

app_name = 'users'

urlpatterns = [
    path('login/', UserLoginView.as_view(), name='login'),
    path('register/', UserRegistrationView.as_view(), name='register'),
    path('logout/', LogoutView.as_view(), name='logout'),
]

main/models.py
from django.core.exceptions import ValidationError
from django.db import models

from users.models import User


class Bookmark(models.Model):
    user = models.ForeignKey(to=User, on_delete=models.CASCADE)
    title = models.CharField(max_length=256)
    url = models.URLField(default='https://')
    description = models.TextField()
    favicon = models.ImageField(upload_to='url_icons', null=True, blank=True)

    def clean(self):
        if Bookmark.objects.filter(user=self.user, url=self.url).exists():
            raise ValidationError('Закладка с введеным URL уже есть!')

    class Meta:
        verbose_name = 'закладка'
        verbose_name_plural = 'закладки'
        constraints = [
            models.UniqueConstraint(fields=['user', 'url'], name='unique_url')
        ]

users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


class User(AbstractUser):
    is_verified_email = models.BooleanField(default=False)
    email = models.EmailField(unique=True)

main/forms.py
from django.forms import ModelForm

from main.models import Bookmark


class BookmarkForm(ModelForm):
    class Meta:
        model = Bookmark
        fields = ('url', )

users/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm

from users.models import User


class UserLoginForm(AuthenticationForm):
    username = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder': 'Введите имя пользвоателя'}))
    password = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': 'Введите пароль'}))

    class Meta:
        model = User
        fields = ('username', 'password')


class UserRegistrationForm(UserCreationForm):
    first_name = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder': 'Введите имя'}))
    last_name = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder': 'Введите фамилию'}))
    username = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder': 'Введите имя пользователя'}))
    email = forms.CharField(widget=forms.EmailInput(attrs={
        'placeholder': 'Введите адрес эл. почты'}))
    password1 = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': 'Введите пароль'}))
    password2 = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': 'Подтвердите пароль'}))

    class Meta:
        model = User
        fields = (
            'first_name',
            'last_name',
            'username',
            'email',
            'password1',
            'password2'
        )

common/views.py
class TitleMixin:
    title = None

    def get_context_data(self, **kwargs):
        context = super(TitleMixin, self).get_context_data()
        context['title'] = self.title
        return context

main/views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse
from django.views.generic import ListView
from django.views.generic.base import TemplateView

from common.views import TitleMixin
from main.forms import BookmarkForm
from main.models import Bookmark
from main.tasks import get_bookmark_info


class IndexView(TitleMixin, TemplateView):
    template_name = 'main/index.html'
    title = 'Bookmarks - Главная'


class BookmarksListView(LoginRequiredMixin, TitleMixin, ListView):
    template_name = 'main/bookmarks.html'
    title = 'Bookmarks - Мои закладки'

    def get_queryset(self):
        return Bookmark.objects.filter(user=self.request.user)


@login_required
def add_bookmark(request):
    if request.method == 'POST':
        bookmark = Bookmark(user=request.user)
        form = BookmarkForm(data=request.POST, instance=bookmark)
        if form.is_valid():
            bookmark.save()
            messages.success(request, 'Вы успешно добавили закладку!')
            get_bookmark_info.delay(request.POST['url'], request.user.id)
            return HttpResponseRedirect(reverse('main:add-bookmark'))
    else:
        form = BookmarkForm()
    context = {
        'form': form,
        'title': 'Bookmarks - Добавить закладку',
    }
    return render(request, 'main/add-bookmark.html', context)

users/views.py
from django.contrib.auth.views import LoginView
from django.contrib.messages.views import SuccessMessageMixin
from django.urls import reverse_lazy
from django.views.generic.edit import CreateView

from common.views import TitleMixin
from users.forms import UserLoginForm, UserRegistrationForm
from users.models import User


class UserLoginView(TitleMixin, LoginView):
    template_name = 'users/login.html'
    form_class = UserLoginForm
    title = 'Bookmarks - Авторизация'


class UserRegistrationView(TitleMixin, SuccessMessageMixin, CreateView):
    model = User
    form_class = UserRegistrationForm
    template_name = 'users/register.html'
    success_url = reverse_lazy('users:login')
    success_message = 'Вы успешно зарегистрировались'
    title = 'Bookmarks - Регистрация'

main/templates/main/add-bookmark.html
{% extends 'main/base.html' %}

{% block content %}
<div class="container">
    <div class="row justify-content-center">
        <div class="col-lg-5">
            {% if messages or form.errors %}
            <div class="alert {% if messages %} alert-success {% else %} alert-warning {% endif %}
                            alert-dismissible fade show" role="alert" style="margin-top: 50px;">
                {% if messages %}
                {% for message in messages %}
                {{ message }}
                {% endfor %}
                {% else %}
                {{ form.errors }}
                {% endif %}
            </div>
            {% endif %}
            <div class="card shadow-lg border-0 rounded-lg mt-5">
                <div class="card-header"><h3 class="text-center font-weight-light my-4">Добавить закладку</h3></div>
                <div class="card-body">
                    <form action="{% url 'main:add-bookmark' %}" method="post">
                        {% csrf_token %}
                        <div class="form-group">
                            <label class="small mb-1" for="{{ form.url.id_for_label }}">
                                URL-адресс закладки
                            </label>
                            {{ form.url }}
                        </div>
                        <div class="form-group d-flex align-items-center justify-content-between mt-4 mb-0">
                            <input class="btn btn-primary" type="submit" value="Добавить">
                        </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

main/templates/main/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title> {{ title }} </title>
        <!-- Favicon-->
        <link rel="icon" type="image/x-icon" href="{% static 'assets/favicon.ico' %}" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="{% static 'css/styles.css' %}" rel="stylesheet" />
    </head>
    <body>

        <!-- Responsive navbar-->
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
            <div class="container">
                <a class="navbar-brand" href="{% url 'index' %}">Bookmarks app</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
                        {% if user.is_authenticated %}
                        <li class="nav-item"><a class="nav-link" href="{% url 'main:my-bookmarks' %}">Мои закладки</a></li>
                        <li class="nav-item"><a class="nav-link" href="{% url 'main:add-bookmark' %}">Добавить закладку</a></li>
                        <li class="nav-item"><a class="nav-link" href="{% url 'users:logout' %}">Выйти</a></li>
                        {% else %}
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" id="navbarDropdown" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">Входи и регистрация</a>
                            <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
                                <li><a class="dropdown-item" href="{% url 'users:login' %}">Войти</a></li>
                                <li><a class="dropdown-item" href="{% url 'users:register' %}">Зарегистрироваться</a></li>
                            </ul>
                        </li>
                        {% endif %}
                    </ul>
                </div>
            </div>
        </nav>
        {% block content %}

        {% endblock %}
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src="{% static 'js/scripts.js' %}"></script>
    </body>
</html>

main/templates/main/bookmarks.html
{% extends 'main/base.html' %}

{% block content %}
{% for bookmark in object_list %}
<div class="list-group">
    <a href="{{ bookmark.url }}" class="list-group-item list-group-item-action flex-column align-items-start">
        <div class="d-flex w-100 justify-content-between">
            <h5 class="mb-1">
                <img width="32" height="32" src="{{ MEDIA_URL }}{{ bookmark.favicon }}" class="img-thumbnail">
                {{ bookmark.title }}
            </h5>
        </div>
        <p class="mb-1">{{ bookmark.description }}</p>
        <small>{{ bookmark.url }}</small>
    </a>
</div>
{% endfor %}
{% endblock %}

main/templates/main/index.html
{% extends 'main/base.html' %}
{% block content %}
        <!-- Page content-->
        <div class="container">
            <div class="text-center mt-5">
                <h1>Добро пожаловать в Bookmarks app</h1>
                <p class="lead">простое приложение для хранения ваших закладок</p>
               {% if user.is_anonymous %}
                <p>войдите или зарегистрируйтесь чтобы начать работу</p>
                {% endif %}
            </div>
        </div>
{% endblock %}

users/templates/users/login.html
{% extends 'main/base.html' %}

{% block content %}
<main>
            <div class="container">
                <div class="row justify-content-center">
                    <div class="col-lg-5">
                        {% if messages or form.non_field_errors %}
                            <div class="alert
                            {% if messages %} alert-success {% else %} alert-warning {% endif %}
                            alert-dismissible fade show" role="alert"
                                 style="margin-top: 50px;">
                                {% if messages %}
                                    {% for message in messages %}
                                        {{ message }}
                                    {% endfor %}
                                {% else %}
                                    {{ form.non_field_errors }}
                                {% endif %}
                            </div>
                        {% endif %}

                        <div class="card shadow-lg border-0 rounded-lg mt-5">
                            <div class="card-header"><h3 class="text-center font-weight-light my-4">Авторизация</h3>
                            </div>
                            <div class="card-body">
                                <form action="{% url 'users:login' %}" method="post">
                                    {% csrf_token %}
                                    <div class="form-group">
                                        <label class="small mb-1" for="{{ form.username.id_for_label }}">
                                            Имя пользователя
                                        </label>
                                        {{ form.username }}
                                    </div>
                                    <div class="form-group">
                                        <label class="small mb-1" for="{{ form.password.id_for_label }}">Пароль</label>
                                        {{ form.password }}
                                    </div>
                                    <div class="form-group d-flex align-items-center justify-content-between mt-4 mb-0">
                                        <a class="small" href="#">Забыли пароль?</a>
                                        <input class="btn btn-primary" type="submit" value="Авторизоваться">
                                    </div>

                                </form>
                            </div>
                            <div class="card-footer text-center">
                                <div class="small"><a href="{% url 'users:register' %}">Нужен аккаунт? Зарегистрируйся!</a></div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </main>
{% endblock %}

users/templates/users/register.html
{% extends 'main/base.html' %}

{% block content %}
<main>
            <div class="container">
                <div class="row justify-content-center">
                    <div class="col-lg-7">
                        {% if form.errors %}
                            <div class="alert alert-warning alert-dismissible fade show" role="alert"
                                 style="margin-top: 50px;">
                                {{ form.errors }}
                                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                </button>
                            </div>
                        {% endif %}
                        <div class="card shadow-lg border-0 rounded-lg mt-5">
                            <div class="card-header"><h3 class="text-center font-weight-light my-4">Создать аккаунт</h3>
                            </div>
                            <div class="card-body">
                                <form action="{% url 'users:register' %}" method="post">
                                    {% csrf_token %}
                                    <div class="form-row">
                                        <div class="col-md-6">
                                            <div class="form-group">
                                                <label class="small mb-1" for="{{ form.first_name.id_for_label">
                                                    Имя
                                                </label>
                                                {{ form.first_name }}
                                            </div>
                                        </div>
                                        <div class="col-md-6">
                                            <div class="form-group">
                                                <label class="small mb-1" for="{{ form.last_name.id_for_label }}">
                                                    Фамилия
                                                </label>
                                                {{ form.last_name }}
                                            </div>
                                        </div>
                                    </div>
                                    <div class="form-row">
                                        <div class="col-md-6">
                                            <label class="small mb-1" for="{{ form.username.id_for_label }}">
                                                Имя пользователя
                                            </label>
                                            {{ form.username }}
                                        </div>
                                        <div class="col-md-6">
                                            <label class="small mb-1" for="{{ form.email.id_for_label }}">
                                                Адрес электронной почты
                                            </label>
                                            {{ form.email }}
                                        </div>
                                    </div>
                                    <div class="form-row">
                                        <div class="col-md-6">
                                            <div class="form-group">
                                                <label class="small mb-1" for="{{ form.password1.id_for_label }}">
                                                    Пароль
                                                </label>
                                                {{ form.password1 }}
                                            </div>
                                        </div>
                                        <div class="col-md-6">
                                            <div class="form-group">
                                                <label class="small mb-1" for="{{ form.password2.id_for_label }}">
                                                    Подтверждение пароля
                                                </label>
                                                {{ form.password2 }}
                                            </div>
                                        </div>
                                    </div>
                                    <div class="form-group mt-4 mb-0">
                                        <input class="btn btn-primary btn-block" type="submit" value="Создать аккаунт">
                                    </div>
                                </form>
                            </div>
                            <div class="card-footer text-center">
                                <div class="small"><a href="{% url 'users:login' %}">Уже есть аккаунт? Авторизоваться</a></div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </main>
{% endblock %}